syntax = "proto3";

package auth;

option go_package = "github.com/Fitray/auth_service/api/proto/auth;auth";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc ValidateAccessToken(ValidateAccessTokenRequest) returns (ValidateAccessTokenResponse);
  rpc Authorize(AuthorizeRequest) returns (AuthorizeResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}

message RegisterRequest {
  string login = 1;
  string password = 2;
}

message RegisterResponse {
  int64 user_id = 1;
}

message LoginRequest {
  string login = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  string access_token = 1;
}

message ValidateAccessTokenRequest {
  string access_token = 1;
}

message ValidateAccessTokenResponse {
  User user = 1;
}

message AuthorizeRequest {
  int64 user_id = 1;
  string permission = 2;
}

message AuthorizeResponse {
  bool allowed = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {}

message User {
  int64 id = 1;
  string login = 2;
}